### ISSUE TITLE
About achieving faster results

### ISSUE THREAD

**Issue by karaposu** [wiktorlazarski/head-segmentation#32]
Hi Guys,  I am using this repo for one of my personal projects and I am quite happy you guys are keeping it updated. 

Head-segmentation part of my app is the bottleneck in terms of speed. I am using CPU bc GPU servers are expensive. I started searching the most popular face-parsing algorithms out there and many of them use relatively complex models to do multiclass segmentation with at least 10 classes (eye, nose, neck, cloth, lips, even left brow and right brows are considered different classes in some cases)  

From my understanding, if we are doing just head+hair area segmentation then we don't need such complex model design and maybe we can alter/reduce the model layers and retrain the network for just head+hair segmentation. In theory, this would result in a lot faster runtime.  Is my way of thinking is correct? 

@wiktorlazarski this repo uses pretrained mobilnet right?

**Comment by Szuumii** [comment]
Hi @karaposu, thanks for reaching out to us! Currently we (me and @wiktorlazarski ) are offline. Let me get back to you with an answer next week 😄

**Comment by karaposu** [comment]
@wiktorlazarski can you share some details about total training time ? Also training is done for input size of 256x256 right?

**Comment by wiktorlazarski** [comment]
Hey @karaposu, thanks for all the questions and sorry for the delay in answering it. Things were quite chaotic on our end so it took me a while to carve out some time to construct answers to all your questions, which pilled up as far as I see.

> From my understanding, if we are doing just head+hair area segmentation then we don't need such complex model design and maybe we can alter/reduce the model layers and retrain the network for just head+hair segmentation. In theory, this would result in a lot faster runtime. Is my way of thinking is correct?

Whether we need such complex architecture or not it's something that is difficult to answer without proper research. To have some insides and be able to answer your question, what I would suggest is to do a sweep over most common for performance focused semantic segmentation neural networks architectures. Hence, the answer to your first question probably will feel a bit unsatisfactory - "It's something that has to be tested and should be estimated". 
In our case, we took the most common, "of the shelf", architecture - UNet and only experiment with ResNet and MobileNet encoders. Also, our use case scenario didn't assume real time usage, so we didn't research that aspect of the model too much. 
Despite that please, feel free to plug different "smaller" architecture like DeepLabV3 and test them. If you'll willing to, please share with us some of your findings. I'd love to have see where this research will take you and also I'd be glad to share my thoughts on the results.
To encourage you more to follow that path, I think that doing some architecture optimisation to gain inference speed-up is possible here for sure! I don't have any doubts that a sweet spot where tradeoff between model's segmentation maps prediction quality performance and time of inference is optimal hasn't been reached by this model yet. If I were you, then apart from architecture sweep, I'd also have a look at techniques like network quantisation and pruning. They may help here as well.

> @wiktorlazarski this repo uses pretrained mobilnet right?

That's not correct, we are using ResNet34 as a feature extractor (aka backbone, aka encoder).

> @wiktorlazarski can you share some details about total training time ? Also training is done for input size of 256x256 right?

Training time is also something that I refuse to indicate as it's not really deterministic. It depends on, for example, amount of GPUs you will use, input image resolution, you'll specify, amount of epochs, you want to perform etc. In our case, as far as I recall and it's been a while since we trained that model so please take it with a huuuuge pinch of salt, those properties were as such:

1) Amount of GPUs = 1
2) Input resolution = (512, 512)
3) Number of epochs = 300
4) Floating point precision = 32

Those I kinda remember, and I'm not super sure about the others.

Almost last words, let me say that that optimising inference time is one of the direction, I'd love this repo to go. If we may provide a bunch of models that cover different use cases that open source community have, that's would be an amazing milestone for that project.

Last but not least, I'm super happy that you decided to go for our solution in your personal project. I don't know any details about it so if you feel like it, please don't hesitate to drop a few lines on it. I'd be keen on reading how and why people use `head_segmentation` package - may be helpful to decide which work streams we should prioritise in the future.

If all your questions have been answered and there is no follow-up questions on your end, please close the issue.

Best regards,
Wiktor

**Comment by karaposu** [comment]
@wiktorlazarski Thank you very much for detailed answer wiktor. I really appreciate it. My first goal is to rerun whole training and then i will start trying what u described

**Comment by karaposu** [comment]
@wiktorlazarski Thank you very much for detailed answer wiktor. I really appreciate it. My first goal is to rerun whole training and then i will start trying what u described
